### ISSUE TITLE
_unsorted

### ISSUE THREAD

**Issue by thunderpwn** [thunderpwn/ETL_renderer2_shaders#2]

**Comment by thunderpwn** [comment]
in this there is a lot of wierd UI stuff that isnt really there..
like : 
`allied_covertops
{
	nomipmaps
	nopicmip
	{
		map ui/assets/portraits/covertops.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}`

@rafal1137 or @mightykemon do any of you know if these are something we need at all?
because there is no textures ...

**Comment by realkemon** [comment]
To me it looks like remnants of rtcw. In ui_mp/assets/portraits are images used for the win screen. They are not used in ET so I think it's safe to remove them.

**Comment by thunderpwn** [comment]
ok, then I will check thru the whole shader and if I dont find anything usefull I will just remove it

**Comment by realkemon** [comment]
Perfect. Thanks

Am 23.02.2017 18:42 schrieb "twt_thunder" <notifications@github.com>:

**Comment by thunderpwn** [comment]
//whole lot of crap here with old stuff from wolfenstein3d it seems, the textures are still left in gfx?!?!
/*jpwhud1
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/classic1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud2
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/pistol1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud3
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/mp401.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud4
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/minigun1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwhud5
{
	cull none
	nofog
	nopicmip
	{
		clampmap gfx/2d/knife1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwtest1
{
	cull none
	entityMergable
	nofog
	{
		clampmap gfx/2d/mp401.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}

jpwtest2
{
	cull none
	entityMergable
	nofog
	{
		clampmap gfx/2d/pistol1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbGen vertex
	}
}
*/

**Comment by realkemon** [comment]
Personally, I'd say remove it, but better to ask on discord or better post
in your ticket.

Am 23.02.2017 18:57 schrieb "twt_thunder" <notifications@github.com>:

**Comment by thunderpwn** [comment]
oki think its done...
a little notice:
Made a texture for gfx/misc called sun.tga since its missing.. Dont know what it is but I also see r2 complaining about it..
